### ISSUE TITLE
Pythonanywhere

### ISSUE THREAD

**Issue by Brianhaaa** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#10]
Is it possible to run this on pythonanywhere?

and if so how?

**Comment by Blockys69** [comment]
Open your main .py file by clicking the name in Dashboard | Files. The file will be opened in edit mode, and you should see a handy 'Save & Run' button at top right.

Or I also did it using the Bash console

**Comment by Brianhaaa** [comment]
PancakeX-ASTRA-V2-BSC-Sniping-Bot-main/astra.py", line 313, in <module>
    B=P.Tk()
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

the problem is the GUI I think

**Comment by Brianhaaa** [comment]
Is there an old version without gui?

**Comment by Blockys69** [comment]
I think there was somewhere but... it's really hard to set up :D Sniping is about being fast and the old one wasn't fast hahaha. You want to use it for market making or why set it up like that?
