### ISSUE TITLE
Non-hexadecimal digit found

### ISSUE THREAD

**Issue by fefuxd** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#11]
Hi, after i Installed i got the following error: Non-hexadecimal digit found

as the image attached.

how can i solve this?

thanks
![Screenshot](https://user-images.githubusercontent.com/31115879/220175166-897b6256-6f72-4fcb-ad60-ef7f5d590d4b.png)

**Comment by DeFiMasterd** [comment]
Hey! Seems like you are inputting the seed phrase into the Private Key field.

Check the image below on how to find a private key of your wallet.

![meta](https://user-images.githubusercontent.com/118478307/220201745-07c106bb-28a7-47e4-a32f-5bb29f329f4b.png)
