### ISSUE TITLE
invalid private key

### ISSUE THREAD

**Issue by bloodysniper3** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#14]
Whenever i put my key in either with spaces or not it keeps saying invalid key. does it only work on a specific wallet? im using trust

**Comment by DeFiMasterd** [comment]
Did you solve your issue? Would love to hear how you solved it for anyone from the community to also know as I never tried Trust wallet. Is it the wallet that exports the private key with 0x? then you just delete the prefix and it should work

**Comment by bloodysniper3** [comment]
I did, I was using seed instead of metamask private key option. So far so good!
