### ISSUE TITLE
token balance not received!!

### ISSUE THREAD

**Issue by Hemankadariya** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#17]
Hi! I put around 0.01 BNB as a test on 'BNB' token address and it show "liquidity deducted". I then sold it but the received token was 0 infact, when i press sell more token was deducted from my metamask however, the price which i have sold was still the same the price i bought. Reason?

**Comment by DeFiMasterd** [comment]
It seems the token had a sell tax, or was a scam token perhaps

**Comment by Hemankadariya** [comment]
i also tried with usdt and bnb token

**Comment by DeFiMasterd** [comment]
Wow, then something really weird is happening. This is an issue I never heard about, please send screenshots
