### ISSUE TITLE
Can you please tell me if it is possible to set the desired price for sale?

### ISSUE THREAD

**Issue by 2007-i** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#19]
Can you please tell me if it is possible to set the desired price for sale? Or can this be done only by the percentage of profit?
And the current price of the token is not visible here?
One more question, does the bot buy until you click sell everything or until there is money in the wallet? Is it possible to set the number of currencies for which you can buy?
Thank you very much for such a product!

**Comment by 2007-i** [comment]
Does the bot buy only for this amount?
![Новый точечный рисунок2](https://user-images.githubusercontent.com/26662266/224788567-dea67ba9-1387-478f-acfd-582cdb851d27.jpg)


And then sells for a fixed% more expensive and again? Or until it makes a profit which is set in the settings?
Thanks for answers!
P.S. adding the current price would be nice.

**Comment by 2007-i** [comment]
By the way, I noticed that you can insert the wallet address only if the keyboard is in the ENG language layout, in other languages ​​"Contr V" is not inserted.

**Comment by DeFiMasterd** [comment]
Yes the bot buys for the amount selected. This is more of a sniping bot than a trading bot. So it buys once liquidity is added and then sells for a % increase and then stops.

I am currently working on a trading bot that will buy and sell infinitely on the pair you choose and make you money directly to the wallet, is that what you are looking for?

wow the crl + v language problem is the first time I hear it :/

**Comment by 2007-i** [comment]
`I am currently working on a trading bot that will buy and sell infinitely on the pair you choose and make you money directly to the wallet, is that what you are looking for?`
Wow, Yesss)

**Comment by 2007-i** [comment]
> Wow, Yesss)



> Yes the bot buys for the amount selected. This is more of a sniping bot than a trading bot. So it buys once liquidity is added and then sells for a % increase and then stops.
> 
> I am currently working on a trading bot that will buy and sell infinitely on the pair you choose and make you money directly to the wallet, is that what you are looking for?
> 
> wow the crl + v language problem is the first time I hear it :/

Wow, Yesss)
Thank you very match!
