### ISSUE TITLE
ModuleNotFoundError: No module named 'web3'

### ISSUE THREAD

**Issue by itsmezenitsu** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#2]
Hi i was installing the program and powershell gave me error saying , line 88, in <module>
    from web3 import Web3 as S
ModuleNotFoundError: No module named 'web3'

**Comment by DeFiMasterd** [comment]
Can you try writing in the terminal: "pip install web3" without double quotes

Did you install the requirements correctly?

**Comment by coodinggeek** [comment]
# Thanks
Hello, DefiMasterd. How are you doing?, First and foremost, thank you for your contribution.
Second, I'd like to know what is the ideal way to study these things; I'm at a loss as to how I should go. The problem is that I am not from a technical background, but I want to learn all of these things. How to Create Your Own Bots (defi).
There is no no reference in udemy or YouTube. So, how should I go about learning?

I'm asking you because you already make stuff, as opposed to a man who sells courses but doesn't know how to make anything.
Your assistance will be much appreciated.

**Comment by itsmezenitsu** [comment]
thx it worked

**Comment by yoshi00** [comment]
Hi i am having this error, i tried to install web 3 and correctly installed the requirements
```line 92, in <module>
    from web3 import Web3 as R
ModuleNotFoundError: No module named 'web3'```

**Comment by DeFiMasterd** [comment]
Hey Yoshi, when you install the requirements.txt you have to install it in the folder where you have the bot. So first open terminal in the folder and once the path on the left is displaying exactly the location of your folder bot THEN type pip install requirements part

**Comment by yoshi00** [comment]
Hey I'm doing it but it seems that the dependencies are not importing. What can it be ? should I try to install manually?
![teste code 1](https://user-images.githubusercontent.com/52901102/224516472-f0d80feb-91db-40a3-8520-8b6452baa93b.png)

**Comment by DeFiMasterd** [comment]
Yes try that out: pip3 install web3

**Comment by yoshi00** [comment]
hey, I'm facing some problems, such as the installation of dependencies for example web3, in addition to showing that it does not find the web3 module, it also shows this. I don't know how to solve this already tried to install visual studio installer to run but nothing happened or changed. Can you help me ?

`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

**Comment by DeFiMasterd** [comment]
This usually happens if you have python version 3.1 where wheel module is not supported. Download and activate python 3.7+ OR follow this tutorial if the issue is still there https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

**Comment by yoshi00** [comment]
Okay thanks, what I did was install Microsoft C++ Build Tools following the settings in this comment on stackoverflow
https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

Then I installed each dependency manually, but using the version of my Python (which in this case is version 3.7.1) so I used the following way for each requirement `python3.7 -m pip install <module name>`, after that run the code with my python version as follows `python3.7 astra.py`. and it worked

**Comment by DeFiMasterd** [comment]
That's fantastic, thank you for writing all the steps down, I am sure it will help somebody in the future
