### ISSUE TITLE
Checksum Error

### ISSUE THREAD

**Issue by ShawnXpro** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#22]
astra.py", line 184, in <module>
    A9=C.toChecksumAddress('0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c')
AttributeError: 'Web3' object has no attribute 'toChecksumAddress'. Did you mean: 'to_checksum_address'?

Got an issue, Sorry, New in coding

**Comment by DeFiMasterd** [comment]
Are you using the correct checksummed address? Copy your address, put it into etherscan and then copy and paste it from there into the GUI

**Comment by ShawnXpro** [comment]
My Wallet address?

**Comment by ShawnXpro** [comment]
I'm using as default given in the code, should i use my wallet address?

**Comment by DeFiMasterd** [comment]
I tried to run it 3 times and everytime works fine. Can you give me exact steps you took after downloading the zip

**Comment by DeFiMasterd** [comment]
Sometimes this error appears when the Web3 module is installed incorrectly

**Comment by DeFiMasterd** [comment]
Updated and fixed
