### ISSUE TITLE
No module named Web3 after installing requirements.txt

### ISSUE THREAD

**Issue by AAZZ123** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#23]
from web3 import Web3 as Q
ModuleNotFoundError: No module named 'web3'

i've got this same error for all your bot, i've searching 5 hours and uninstall py, install again.. do the same and search i don't found the solution !

**Comment by DeFiMasterd** [comment]
Have you tried direct module install: "pip3 install web3" ?

If you installed the requirements txt then you should have it. This error usually appears when you installed requirements outside of the bot folder

**Comment by AAZZ123** [comment]
![astrapy](https://user-images.githubusercontent.com/35351379/228241382-d33d6c8d-da44-4909-baa7-c937e4432c63.png)
i don't know what's the problem

**Comment by DeFiMasterd** [comment]
Ask in discord: https://discord.gg/65jnwkdA

**Comment by DeFiMasterd** [comment]
You are 100% installing Web3 outside of the bot folder. Either that or you are using old version of python. pip3 install web3
