### ISSUE TITLE
Inquiry: Is It Possible for Manually Set Buy Price?

### ISSUE THREAD

**Issue by DALE4804** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#24]
Sir, may I ask if it is possible to set the buy price manually?
As we know there are so many tokens that go below TGE price like 200%.
For example, the token price is now 0.005 but there are so  many investor that bought on presale so I want to set/snipe buy order for example at 0.0025 and wait if the buy order be filled?

Thank you and more power!!!

**Comment by DeFiMasterd** [comment]
https://github.com/Meetytoes/BSC-Token-Trading-Bot-AES 

What about this?

**Comment by DALE4804** [comment]
Thanks you... and will check this one..

**Comment by DALE4804** [comment]
ahh there is wacatac in it...

**Comment by DeFiMasterd** [comment]
There is not, python files don't run those + it's a good friend of mine that coded that one.

It's coded in python + tkinter
