### ISSUE TITLE
All of my transactions get cancelled

### ISSUE THREAD

**Issue by Darknezzx** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#25]
Every transaction i sniped gets cancelled. How can i contact you to show you bscscans and etc.?

![image](https://user-images.githubusercontent.com/79605632/229367223-36537100-6796-4ae8-961d-4b895718dc8b.png)
my settings

**Comment by DeFiMasterd** [comment]
People chat a bit about our bots on the https://discord.gg/65jnwkdA Crypto alpha channel
