### ISSUE TITLE
Sniping-Bot Error: 'buildTransaction' attribute not found after package updates

### ISSUE THREAD

**Issue by jessfortemnaturae8717** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#26]
Once the buy order is initiated. I receive the following error message: 

Something went wrong with the transaction
'swapExactETHforTokensSupportingFeeOnTransferTokens' object has no attribute 'buildTransaction'.

I did have to install the most recent version(s) of cryptography and pyclip (not pyperclip). 

Can someone help me figure out why the attribute isn't there? I've also attached a screenshot: 
![snipbot_error](https://user-images.githubusercontent.com/25465107/229560954-82ae3f54-8ea7-4de7-9688-7317e6fb9d28.PNG)

```
def C0():
	j()
	try:
		F=B.eth.contract(I,abi=T);C=F.functions.balanceOf(a.get()).call()
		if A4.get():D=0
		else:D=M(C-C*M(Ag)/100)
		A(BV, X)
		H = U.functions.swapExactETHForTokensSupportingFeeOnTransferTokens(M(D), [A9, I], G, M(
			AW())+900).buildTransaction({AR: G, 'value': B.toWei(r, Y), An: M(A5), AS: B.toWei(A6, Ao), AT: B.eth.get_transaction_count(G)})
		K = B.eth.account.sign_transaction(H, private_key=V)
		E = B.eth.send_raw_transaction(K.rawTransaction)
		A(BW, O)
		A(B0+B.toHex(E), O)
		B.eth.waitForTransactionReceipt(E, timeout=900)
		C9()
	except A7 as L:
		A(B1, J)
		A(L, J)
		A1()
		return
C1='gAAAAABh80KOUysGNn39XTwSm-HHvOIkoWcJhmk0HtVug7bMgvto83_ZCSQ9rdf86LaJEINYzXTqbRO8EDtcMziHy2PwfjdqW_0VsOwYg1x4GWADOsNo17E='
```

**Comment by DeFiMasterd** [comment]
Okay that looks like you over upgraded your Web3 version. Uninstall it and install python 3.7 + install requierement txt. You installed Web3 newest version and the bot doesn't work with that
