### ISSUE TITLE
Trading pair

### ISSUE THREAD

**Issue by 2007-i** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#28]
Hello Friend.
Please tell me if I want to make a trading pair not bnb but another one, where should I change it?
`A9=B.to_checksum_address('0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c')`
Thank!

**Comment by DeFiMasterd** [comment]
That's a bit too complex, what trading pair you want
