### ISSUE TITLE
Antibot antisniper

### ISSUE THREAD

**Issue by Boody1990** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#29]
Does it bypass antibot and antisniper measures ?

**Comment by DeFiMasterd** [comment]
Yes it does, it bypass honeypot contracts and antisniper buy waiting the perfect time

**Comment by Boody1990** [comment]
Thanks alot man but i want to ask you if they list the token on cex 10 min before dex when they add liquidity to pcs will price be instantly same as cex or the price go up gradually so the bot has a chance of buying lower ?
Can they really make tax like 90 % in the first milliseconds to rekt bots ?
