### ISSUE TITLE
Learning 

### ISSUE THREAD

**Issue by coodinggeek** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#3]
# Thanks
Hello, DefiMasterd. How are you doing?, First and foremost, thank you for your contribution.
Second, I'd like to know what is the ideal way to study these things; I'm at a loss as to how I should go. The problem is that I am not from a technical background, but I want to learn all of these things. How to Create Your Own Bots (defi).
There is no no reference in udemy or YouTube. So, how should I go about learning?

I'm asking you because you already make stuff, as opposed to a man who sells courses but doesn't know how to make anything.
Your assistance will be much appreciated.

**Comment by DeFiMasterd** [comment]
Hey man!

You are welcome and thank you for writing this comment. I would HIGHLY recommend you watch the "Eattheblocks" youtube series that was my starting point together with the entire crypto zombies, open zepellin course
