### ISSUE TITLE
Lp bnb but buy using busd 

### ISSUE THREAD

**Issue by Boody1990** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#30]
Can it buy using busd if the liquidity pool is bnb i mean the token is against bnb ?

**Comment by DeFiMasterd** [comment]
No, it can't routing is on the list of to-dos. Thanks for asking <3

**Comment by Boody1990** [comment]
Can it buy using usdt instead of busd ?

**Comment by DeFiMasterd** [comment]
> Can it buy using usdt instead of busd ?

Yes I am working on that addition :)
