### ISSUE TITLE
Hey mate i am getting the issue of InValid License Key 

### ISSUE THREAD

**Issue by coodinggeek** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#4]
I am getting invalid License Key just wanna confirm is it open source or is it paid?

**Comment by DeFiMasterd** [comment]
Hey! it is completely free as it's a DeFi grant project, let me check if it's throwing an error for me, one sec

**Comment by DeFiMasterd** [comment]
Updated and fixed!

**Comment by DeFiMasterd** [comment]
Download the astra.py again

**Comment by coodinggeek** [comment]
It's working bro, thanks
