### ISSUE TITLE
 private key exposed

### ISSUE THREAD

**Issue by javafish** [DeFiMasterd/PancakeX-ASTRA-V2-BSC-Sniping-Bot#6]
Hi, all my tokens in the wallet have been stolen, and the only place I may expose my private key are your code. Can you please help and give me my token back?

**Comment by DeFiMasterd** [comment]
Responded in the other topic

**Comment by kurtdb** [comment]
Had the same happen to me, so I will be reporting this to GitHub to get your repositories removed.

**Comment by javafish** [comment]
> Had the same happen to me, so I will be reporting this to GitHub to get your repositories removed.

Yes, my wallet is very pure and only used for this guy' code. How can we get our money back?

**Comment by kurtdb** [comment]
You will most likely never see your money again. (unless he suggests a refund) Did he really contact you as he stated in the other comment?

His wallet is https://debank.com/profile/0xfaa5056bc599c24c32e53d8bfd355b33a880f29c, so clearly he has also done this to other people.

**Comment by javafish** [comment]
> You will most likely never see your money again. (unless he suggests a refund) Did he really contact you as he stated in the other comment?
> 
> His wallet is https://debank.com/profile/0xfaa5056bc599c24c32e53d8bfd355b33a880f29c, so clearly he has also done this to other people.

No, he just said his code will not steal private key. How much you lost and anything we can do?
